### ISSUE TITLE
bflyt convertion issue.

### ISSUE THREAD

**Issue by ghost** [Tyulis/ALYTtool#1]
original bflyt to tflyt is fine, but tflyt to bflyt doesn't give the same output as the original bflyt even without addition changes to tflyt's content. images wont show up in game with the new file.

sample:
bytes in the frame are the only differences.
![image](https://user-images.githubusercontent.com/19739613/29092426-4c04389a-7c54-11e7-908a-1fe1c6145a17.png)

sample bflyt:

[telop_coming_disaster.zip](https://github.com/Tyulis/ALYTtool/files/1209413/telop_coming_disaster.zip)

edit:
length calculation issue.
easy fix as below.
![image](https://user-images.githubusercontent.com/19739613/29136012-ecd987f6-7d09-11e7-84e2-c86b3e4d2f76.png)

**Comment by Tyulis** [comment]
Fixed. Thanks!
